# Generated by Django 3.0.4 on 2020-03-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_item_list_integrity_cascade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list', 'text')},
        ),
    ]
